20 json schema
INF2-3/api pull request #21
Opened 2023-03-28 08:03 UTC by Jessev3

2023-03-28 08:12 UTC, Mappeldorn requested changes

2023-03-28 08:12 UTC, Mappeldorn commented on api/src/main/resources/schemas/test.xml
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Dit schema kan weg?

2023-03-28 08:12 UTC, Mappeldorn commented on api/src/main/java/com/quintor/api/validators/SchemaValidator.java
> +        String url = "http://localhost:8080/MT940to" + validatorType.toUpperCase();
Zet de url: http://localhost:8080/ in een env bestand

2023-03-28 08:12 UTC, Mappeldorn commented on api/src/main/resources/schemas/schema.json
> +{
Zet in de bestandsnaam waar het schema voor is dus: bankStatementSchema.json. Ook voor de xml

2023-03-28 08:12 UTC, Mappeldorn commented on api/src/main/resources/schemas/schema.json
> +  "description": "This schema validates the custom json file that gets parsed by the JSONParser",
Een korte beschrijving waar het schema voor is

2023-03-28 08:35 UTC, FrancaBaars requested changes

2023-03-28 08:35 UTC, FrancaBaars commented on api/src/main/java/com/quintor/api/mongoConnection/Mt940Controller.java
> +import org.springframework.http.HttpStatus;
Hier graag nog de ongebruikte imports weghalen

2023-03-28 08:35 UTC, FrancaBaars commented on api/src/main/java/com/quintor/api/validators/JSONSchemaValidator.java
Zou je nog commentaar boven de methodes willen zetten

2023-03-28 13:43 UTC, FrancaBaars requested changes

2023-03-28 13:43 UTC, FrancaBaars commented on api/src/main/resources/.env
Wil je de .env file nog aan de .gitignore toevoegen

2023-03-29 07:50 UTC, Mappeldorn approved these changes

2023-03-30 08:56 UTC, FrancaBaars approved these changes

2023-03-30 08:57 UTC, merged