13 get transaction
INF2-3/api pull request #23
Opened 2023-03-30 12:46 UTC by FrancaBaars

2023-03-30 19:48 UTC, Mappeldorn requested changes

2023-03-30 19:48 UTC, Mappeldorn commented on api/src/main/java/com/quintor/api/postgresql/ConnectionPostgres.java
> +    private static final String url = "jdbc:postgresql://localhost:5432/postgres";
deze url in env bestand zetten

2023-03-30 20:02 UTC, Jessev3 commented on api/src/main/java/com/quintor/api/postgresql/ConnectionPostgres.java
> +        while (result.next()) {
als er niks in de database staat veroorzaakt dit een NullPointerException

2023-04-03 08:06 UTC, Noizeisdead approved these changes

2023-04-04 07:44 UTC, Jessev3 approved these changes

2023-04-04 08:19 UTC, Mappeldorn approved these changes

2023-04-04 08:19 UTC, merged