6 bankafschrift opslaan postgresql json
INF2-3/api pull request #24
Opened 2023-04-03 07:57 UTC by Noizeisdead

2023-04-03 08:38 UTC, Jessev3 commented on api/src/main/java/com/quintor/api/postgreSqlConnection/Json.java
> +package com.quintor.api.mt940;
De package klopt niet aangezien het bestand in postgresSqlConnection staat

2023-04-03 08:39 UTC, Jessev3 commented on api/src/main/java/com/quintor/api/postgreSqlConnection/Json.java
Denk dat het handig is om deze klasse een meer specifieke naam te geven ipv alleen Json

2023-04-03 08:41 UTC, Jessev3 commented on api/src/main/java/com/quintor/api/postgreSqlConnection/PostgreSqlController.java
> +        JSONObject json = (JSONObject) parser.parse(jsonString);
JSONParser is deprecated staat er. Om string naar json te parsen kan je 'new JSONObject(jsonString)' gebruiken

2023-04-03 08:42 UTC, Jessev3 commented on api/src/main/java/com/quintor/api/postgreSqlConnection/PostgreSqlController.java
> +          //  preparedStatement.executeUpdate();
Moeten de code die uitgecomment is nog gebruikt worden of kan dat weg

2023-04-03 08:53 UTC, Jessev3 commented on api/pom.xml
> +        </dependency>
Deze dependency weghalen en die van org.json die in de andere branches staat gebruiken

2023-04-03 08:54 UTC, Jessev3 commented on api/src/main/java/com/quintor/api/postgreSqlConnection/PostgreSqlController.java
Ongebruikte imports weghalen

2023-04-03 09:19 UTC, FrancaBaars requested changes
Graag nog comments boven alle methodes zetten

2023-04-03 09:19 UTC, FrancaBaars commented on Docker/database-data/mongodb/WiredTiger.turtle
Zou je het mapje database-date in de .gitignore willen zetten. Deze bestanden zijn anders voor iedereen.

2023-04-03 09:19 UTC, FrancaBaars commented on api/src/main/java/com/quintor/api/postgreSqlConnection/PostgreSqlController.java
> +        System.out.println("in endpoint");
Hier graag nog de system.out.println weghalen

2023-04-03 09:19 UTC, FrancaBaars commented on api/src/main/resources/quintor.sql
Dit is niet de laatste versie van het sql bestand. Dit graag nog updaten

2023-04-04 09:03 UTC, Jessev3 approved these changes

2023-04-04 13:34 UTC, FrancaBaars requested changes

2023-04-04 13:34 UTC, FrancaBaars commented on api/src/main/resources/quintor.sql
Dit is een sql bestand met een andere naam, ik zou dan of deze weghalen of de naam veranderen naar postgres.sql. In jesse zijn branch staat op dit moment de laatste versie van het sql bestand

2023-04-04 18:23 UTC, Mappeldorn approved these changes

2023-04-05 08:34 UTC, FrancaBaars commented on api/src/main/resources/storedPorcedures
Wil je dit bestand in een mapje zetten met Stored procedures, en de typefout uit de naam willen halen

2023-04-05 08:34 UTC, FrancaBaars commented on api/src/main/resources/postgres.sql
Er staat nu 2x een .sql bestand in de resources

2023-04-05 12:44 UTC, FrancaBaars approved these changes

2023-04-05 12:44 UTC, merged