Transaction schemas
INF2-3/api pull request #26
Opened 2023-04-04 13:35 UTC by Jessev3

2023-04-04 14:09 UTC, FrancaBaars requested changes

2023-04-04 14:09 UTC, FrancaBaars commented on api/src/main/resources/postgresql/postgres.sql
> +(1,	'2020-05-22',	'522',	'c',	'$254.00',	'fds',	'hgfd',	'gfd',	'gfd',	1,	'Dit gaat een heel verhaal zijn, om te testen of de beschrijving laten zien op de frontend het doet.',	1,	1),
Hier graag nog een 0 voor de 522 zetten. De validator zegt hierdoor dat het niet valide is.

2023-04-05 07:34 UTC, Noizeisdead approved these changes

2023-04-06 10:49 UTC, FrancaBaars requested changes
XML schema is niet helemaal correct dit nog even veranderen

2023-04-06 11:02 UTC, FrancaBaars approved these changes

2023-04-06 11:02 UTC, merged